name: practice work

on:                               
  push:      
    branches:
    - main
    
jobs:                               
  build-and-deploy:                 
    runs-on : ubuntu-latest          
    steps:                            
    - name: Checkout                  
      uses: actions/checkout@v4                  
                                                 
    - name: configure AWS credentials       
      uses: aws-actions/configure-aws-credetial@v1               
      with:                                                      
           aws-access-key-id : ${{ secrets.AWS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
           aws-region:            eu-north-1                     
    - name: deploy static site to s3 bucket                  
      run: aws s3 sync . s3://tws-my-s3-prac-bucket-50 --delete
