name: practice work

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
 # # --- SonarQube Scan (development branch only) ---
      - name: Set up Java for SonarQube
        if: github.ref_name == 'development'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: SonarQube Scan
        if: github.ref_name == 'development'
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Extract SonarQube Task Info
        if: github.ref_name == 'development'
        id: sonar_task
        run: |
          if [ -f .scannerwork/report-task.txt ]; then
            CE_TASK_ID=$(grep "^ceTaskId=" .scannerwork/report-task.txt | cut -d'=' -f2)
            CE_TASK_URL=$(grep "^ceTaskUrl=" .scannerwork/report-task.txt | cut -d'=' -f2)
            ANALYSIS_ID=$(grep "^analysisId=" .scannerwork/report-task.txt | cut -d'=' -f2)
            echo "ceTaskId=$CE_TASK_ID" >> $GITHUB_OUTPUT
            echo "ceTaskUrl=$CE_TASK_URL" >> $GITHUB_OUTPUT
            echo "analysisId=$ANALYSIS_ID" >> $GITHUB_OUTPUT
            echo "✅ Extracted task info: ceTaskId=$CE_TASK_ID"
          else
            echo "❌ report-task.txt not found!"
            exit 1
          fi

      - name: Check SonarQube Quality Gate
        if: github.ref_name == 'development'
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          CE_TASK_ID: ${{ steps.sonar_task.outputs.ceTaskId }}
        run: |
          chmod +x .github/scripts/check_quality_gate.py
          python3 .github/scripts/check_quality_gate.py
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: List Buckets
        run: aws s3 ls

      - name: Deploy static site to S3 bucket
        run: aws s3 sync . s3://mu-bucket-file-30 --delete
